// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteAVD(arg1:string):Promise<void>;

export function GetAvdDiskUsage(arg1:string):Promise<string>;

export function GetAvdInfo(arg1:string):Promise<models.AvdInfo>;

export function ListAVDs():Promise<Array<string>>;

export function ListRunningAVDs():Promise<Array<string>>;

export function OpenAvdFolder(arg1:string):Promise<void>;

export function RenameAVD(arg1:string,arg2:string):Promise<void>;

export function StartAVD(arg1:string,arg2:boolean):Promise<string>;

export function StopAVD(arg1:string):Promise<void>;
