// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAVD(arg1) {
  return window['go']['manager']['AvdManager']['DeleteAVD'](arg1);
}

export function GetAvdDiskUsage(arg1) {
  return window['go']['manager']['AvdManager']['GetAvdDiskUsage'](arg1);
}

export function GetAvdInfo(arg1) {
  return window['go']['manager']['AvdManager']['GetAvdInfo'](arg1);
}

export function ListAVDs() {
  return window['go']['manager']['AvdManager']['ListAVDs']();
}

export function ListRunningAVDs() {
  return window['go']['manager']['AvdManager']['ListRunningAVDs']();
}

export function OpenAvdFolder(arg1) {
  return window['go']['manager']['AvdManager']['OpenAvdFolder'](arg1);
}

export function RenameAVD(arg1, arg2) {
  return window['go']['manager']['AvdManager']['RenameAVD'](arg1, arg2);
}

export function StartAVD(arg1, arg2) {
  return window['go']['manager']['AvdManager']['StartAVD'](arg1, arg2);
}

export function StopAVD(arg1) {
  return window['go']['manager']['AvdManager']['StopAVD'](arg1);
}
