// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAVD(arg1) {
  return window['go']['app']['App']['DeleteAVD'](arg1);
}

export function GetAndroidSdkEnv() {
  return window['go']['app']['App']['GetAndroidSdkEnv']();
}

export function GetAvdDiskUsage(arg1) {
  return window['go']['app']['App']['GetAvdDiskUsage'](arg1);
}

export function GetAvdInfo(arg1) {
  return window['go']['app']['App']['GetAvdInfo'](arg1);
}

export function ListAVDs() {
  return window['go']['app']['App']['ListAVDs']();
}

export function ListRunningAVDs() {
  return window['go']['app']['App']['ListRunningAVDs']();
}

export function OpenAvdFolder(arg1) {
  return window['go']['app']['App']['OpenAvdFolder'](arg1);
}

export function OpenConfigFolder() {
  return window['go']['app']['App']['OpenConfigFolder']();
}

export function OpenEnvironmentVariables() {
  return window['go']['app']['App']['OpenEnvironmentVariables']();
}

export function RenameAVD(arg1, arg2) {
  return window['go']['app']['App']['RenameAVD'](arg1, arg2);
}

export function SelectAndSaveSdkPath() {
  return window['go']['app']['App']['SelectAndSaveSdkPath']();
}

export function StartAVD(arg1, arg2) {
  return window['go']['app']['App']['StartAVD'](arg1, arg2);
}

export function StopAVD(arg1) {
  return window['go']['app']['App']['StopAVD'](arg1);
}
