// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvVariables() {
  return window['go']['app']['App']['GetEnvVariables']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function ListAVDs() {
  return window['go']['app']['App']['ListAVDs']();
}

export function ListRunningAVDs() {
  return window['go']['app']['App']['ListRunningAVDs']();
}

export function StartAVD(arg1, arg2) {
  return window['go']['app']['App']['StartAVD'](arg1, arg2);
}

export function StopAVD(arg1) {
  return window['go']['app']['App']['StopAVD'](arg1);
}
