// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvVariables():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function ListAVDs():Promise<Array<string>>;

export function ListRunningAVDs():Promise<Array<string>>;

export function StartAVD(arg1:string,arg2:boolean):Promise<string>;

export function StopAVD(arg1:string):Promise<void>;
