// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {helper} from '../models';

export function GetAndroidSdkEnv():Promise<helper.SdkInfo>;

export function OpenConfigFolder():Promise<void>;

export function OpenEnvironmentVariables():Promise<void>;

export function SelectAndSaveSdkPath():Promise<string>;
