// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAcceleration() {
  return window['go']['services']['SystemService']['CheckAcceleration']();
}

export function GetAndroidSdkEnv() {
  return window['go']['services']['SystemService']['GetAndroidSdkEnv']();
}

export function OpenConfigFolder() {
  return window['go']['services']['SystemService']['OpenConfigFolder']();
}

export function OpenEnvironmentVariables() {
  return window['go']['services']['SystemService']['OpenEnvironmentVariables']();
}

export function SelectAndSaveSdkPath() {
  return window['go']['services']['SystemService']['SelectAndSaveSdkPath']();
}
